[package]
name = "paramspider"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
rand = "0.9"
reqwest = { version = "0.13.1", features = ["blocking", "rustls"] }
url = "2"
